openapi: 3.0.0
info:
  title: Prompt Response API
  description: An API that accepts a user prompt/query and returns an AI-generated response.
  version: 1.0.0
paths:
  /prompt-response/:
    post:
      summary: Get AI Response
      description: |
        This endpoint accepts a user query/prompt and returns an AI-generated response using OpenAI's API.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The user query or prompt for the AI model.
              required:
                - prompt
      responses:
        '200':
          description: AI response generated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The AI-generated response to the prompt.
        '400':
          description: Bad request due to missing prompt.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "The 'prompt' field is required."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred."

servers:
  - url: https://ecfsalesai-c7g9gtgmeceacggk.eastus2-01.azurewebsites.net
    description: Local development server
